import { Anton, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

const anton = Anton({
  variable: "--font-title",
  subsets: ["latin"],
  weight: "400"
});

const bricolage_grotesque = Bricolage_Grotesque({
  variable: "--font-default",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bencso",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${anton.variable} ${bricolage_grotesque.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
